branch-defaults:
  master:
    environment: bash-city
    group_suffix: null
environment-defaults:
  bash-city:
    branch: null
    repository: null
global:
  application_name: bash-city
  branch: master
  default_ec2_keyname: bash-city
  default_platform: PHP 7.0
  default_region: us-east-1
  profile: null
  repository: bash-city
  sc: git
