branch-defaults:
  master:
    environment: null
    group_suffix: null
environment-defaults:
  bash-city:
    branch: master
    repository: bash-city
global:
  application_name: bash-city
  branch: master
  default_ec2_keyname: bash-city
  default_platform: PHP 7.0
  default_region: us-east-1
  profile: null
  repository: bash-city
  sc: git
